//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRoute.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eRoute.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Report.
        /// </summary>
        public static string AnalysisReport {
            get {
                return ResourceManager.GetString("AnalysisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApproveAssesment.
        /// </summary>
        public static string ApproveAssesment {
            get {
                return ResourceManager.GetString("ApproveAssesment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApproveList.
        /// </summary>
        public static string ApproveList {
            get {
                return ResourceManager.GetString("ApproveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assesment.
        /// </summary>
        public static string Assesment {
            get {
                return ResourceManager.GetString("Assesment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssesmentRoute.
        /// </summary>
        public static string AssesmentRoute {
            get {
                return ResourceManager.GetString("AssesmentRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditor.
        /// </summary>
        public static string Auditor {
            get {
                return ResourceManager.GetString("Auditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnAdd.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnAssesment.
        /// </summary>
        public static string BtnAssesment {
            get {
                return ResourceManager.GetString("BtnAssesment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnCloseDay.
        /// </summary>
        public static string BtnCloseDay {
            get {
                return ResourceManager.GetString("BtnCloseDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnComplete.
        /// </summary>
        public static string BtnComplete {
            get {
                return ResourceManager.GetString("BtnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnDelete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnExit.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnOpenDay.
        /// </summary>
        public static string BtnOpenDay {
            get {
                return ResourceManager.GetString("BtnOpenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnRefusal.
        /// </summary>
        public static string BtnRefusal {
            get {
                return ResourceManager.GetString("BtnRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnReNew.
        /// </summary>
        public static string BtnReNew {
            get {
                return ResourceManager.GetString("BtnReNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnRevaluation.
        /// </summary>
        public static string BtnRevaluation {
            get {
                return ResourceManager.GetString("BtnRevaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnSearch.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BtnUpdate.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to change your password..
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of.
        /// </summary>
        public static string ChangePasswordMinimum {
            get {
                return ResourceManager.GetString("ChangePasswordMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters in length..
        /// </summary>
        public static string CharLen {
            get {
                return ResourceManager.GetString("CharLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckedUnchecked.
        /// </summary>
        public static string CheckedUnchecked {
            get {
                return ResourceManager.GetString("CheckedUnchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeList.
        /// </summary>
        public static string CodeList {
            get {
                return ResourceManager.GetString("CodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPasswordDoesNorMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordDoesNorMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conformity Assessment.
        /// </summary>
        public static string ConformityAssessment {
            get {
                return ResourceManager.GetString("ConformityAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescList.
        /// </summary>
        public static string DescList {
            get {
                return ResourceManager.GetString("DescList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        public static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorAddSusList.
        /// </summary>
        public static string ErrorAddSusList {
            get {
                return ResourceManager.GetString("ErrorAddSusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorClose.
        /// </summary>
        public static string ErrorClose {
            get {
                return ResourceManager.GetString("ErrorClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCodeDistinctList.
        /// </summary>
        public static string ErrorCodeDistinctList {
            get {
                return ResourceManager.GetString("ErrorCodeDistinctList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorComplete.
        /// </summary>
        public static string ErrorComplete {
            get {
                return ResourceManager.GetString("ErrorComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorConfirmDelete.
        /// </summary>
        public static string ErrorConfirmDelete {
            get {
                return ResourceManager.GetString("ErrorConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorNameEmptyList.
        /// </summary>
        public static string ErrorNameEmptyList {
            get {
                return ResourceManager.GetString("ErrorNameEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorOpen.
        /// </summary>
        public static string ErrorOpen {
            get {
                return ResourceManager.GetString("ErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorOrderOnlyNumberList.
        /// </summary>
        public static string ErrorOrderOnlyNumberList {
            get {
                return ResourceManager.GetString("ErrorOrderOnlyNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorRefusal.
        /// </summary>
        public static string ErrorRefusal {
            get {
                return ResourceManager.GetString("ErrorRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorReOpen.
        /// </summary>
        public static string ErrorReOpen {
            get {
                return ResourceManager.GetString("ErrorReOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorSelectRoute.
        /// </summary>
        public static string ErrorSelectRoute {
            get {
                return ResourceManager.GetString("ErrorSelectRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field Is Required..
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string Grid_Access {
            get {
                return ResourceManager.GetString("Grid_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password at Next Login.
        /// </summary>
        public static string Grid_ChangePassword {
            get {
                return ResourceManager.GetString("Grid_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Grid_Code {
            get {
                return ResourceManager.GetString("Grid_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expired.
        /// </summary>
        public static string Grid_Expiration {
            get {
                return ResourceManager.GetString("Grid_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Edit.
        /// </summary>
        public static string Grid_LastEdit {
            get {
                return ResourceManager.GetString("Grid_LastEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Grid_Name {
            get {
                return ResourceManager.GetString("Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Grid_Number {
            get {
                return ResourceManager.GetString("Grid_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Grid_Type {
            get {
                return ResourceManager.GetString("Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Grid_User {
            get {
                return ResourceManager.GetString("Grid_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Period.
        /// </summary>
        public static string Grid_Validity {
            get {
                return ResourceManager.GetString("Grid_Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string IfYouDontHaveAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageFile.
        /// </summary>
        public static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageOutlet.
        /// </summary>
        public static string ImageOutlet {
            get {
                return ResourceManager.GetString("ImageOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagesRoute.
        /// </summary>
        public static string ImagesRoute {
            get {
                return ResourceManager.GetString("ImagesRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputReasonsForRefusal.
        /// </summary>
        public static string InputReasonsForRefusal {
            get {
                return ResourceManager.GetString("InputReasonsForRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string InvalidChangePassword {
            get {
                return ResourceManager.GetString("InvalidChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string InvalidNewOldPassword {
            get {
                return ResourceManager.GetString("InvalidNewOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rigistration was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string InvalidRegistration {
            get {
                return ResourceManager.GetString("InvalidRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Report.
        /// </summary>
        public static string ManagementReport {
            get {
                return ResourceManager.GetString("ManagementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCP Updates.
        /// </summary>
        public static string MCPUpdates {
            get {
                return ResourceManager.GetString("MCPUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthFrom.
        /// </summary>
        public static string MonthFrom {
            get {
                return ResourceManager.GetString("MonthFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonthTo.
        /// </summary>
        public static string MonthTo {
            get {
                return ResourceManager.GetString("MonthTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string MustBeLong {
            get {
                return ResourceManager.GetString("MustBeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameCategory.
        /// </summary>
        public static string NameList {
            get {
                return ResourceManager.GetString("NameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotYetAssesment.
        /// </summary>
        public static string NotYetAssesment {
            get {
                return ResourceManager.GetString("NotYetAssesment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnFailureAss.
        /// </summary>
        public static string OnFailureAss {
            get {
                return ResourceManager.GetString("OnFailureAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnSuccessAss.
        /// </summary>
        public static string OnSuccessAss {
            get {
                return ResourceManager.GetString("OnSuccessAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnTheList.
        /// </summary>
        public static string OnTheList {
            get {
                return ResourceManager.GetString("OnTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderList.
        /// </summary>
        public static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherReasons.
        /// </summary>
        public static string OtherReasons {
            get {
                return ResourceManager.GetString("OtherReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutletID.
        /// </summary>
        public static string OutletID {
            get {
                return ResourceManager.GetString("OutletID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutletName.
        /// </summary>
        public static string OutletName {
            get {
                return ResourceManager.GetString("OutletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string PasswodAgain {
            get {
                return ResourceManager.GetString("PasswodAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password at next entry.
        /// </summary>
        public static string PasswordChangeNext {
            get {
                return ResourceManager.GetString("PasswordChangeNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of.
        /// </summary>
        public static string PasswordMinimum {
            get {
                return ResourceManager.GetString("PasswordMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity of the password.
        /// </summary>
        public static string PasswordValidity {
            get {
                return ResourceManager.GetString("PasswordValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string PleaseEnter {
            get {
                return ResourceManager.GetString("PleaseEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReasonForOpeningDay.
        /// </summary>
        public static string ReasonForOpeningDay {
            get {
                return ResourceManager.GetString("ReasonForOpeningDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReasonsForRefusal.
        /// </summary>
        public static string ReasonsForRefusal {
            get {
                return ResourceManager.GetString("ReasonsForRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Мe?.
        /// </summary>
        public static string RememberМe {
            get {
                return ResourceManager.GetString("RememberМe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Audit.
        /// </summary>
        public static string RetailAudit {
            get {
                return ResourceManager.GetString("RetailAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteID.
        /// </summary>
        public static string RouteID {
            get {
                return ResourceManager.GetString("RouteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteImagesNot.
        /// </summary>
        public static string RouteImagesNot {
            get {
                return ResourceManager.GetString("RouteImagesNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteName.
        /// </summary>
        public static string RouteName {
            get {
                return ResourceManager.GetString("RouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Supervisor.
        /// </summary>
        public static string SalesSupervisor {
            get {
                return ResourceManager.GetString("SalesSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchBy.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security criteria are required.
        /// </summary>
        public static string SecurityCriteria {
            get {
                return ResourceManager.GetString("SecurityCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAll.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectCheck.
        /// </summary>
        public static string SelectCheck {
            get {
                return ResourceManager.GetString("SelectCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectList.
        /// </summary>
        public static string SelectList {
            get {
                return ResourceManager.GetString("SelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeleteLang.
        /// </summary>
        public static string SeleteLang {
            get {
                return ResourceManager.GetString("SeleteLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusOpenColse.
        /// </summary>
        public static string StatusOpenColse {
            get {
                return ResourceManager.GetString("StatusOpenColse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SumRoute.
        /// </summary>
        public static string SumRoute {
            get {
                return ResourceManager.GetString("SumRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeST.
        /// </summary>
        public static string TimeST {
            get {
                return ResourceManager.GetString("TimeST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeList.
        /// </summary>
        public static string TreeList {
            get {
                return ResourceManager.GetString("TreeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UCN.
        /// </summary>
        public static string UCN {
            get {
                return ResourceManager.GetString("UCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to create a new account..
        /// </summary>
        public static string UseFormBelow {
            get {
                return ResourceManager.GetString("UseFormBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserDefaultError {
            get {
                return ResourceManager.GetString("UserDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YearST.
        /// </summary>
        public static string YearST {
            get {
                return ResourceManager.GetString("YearST", resourceCulture);
            }
        }
    }
}
