#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebManageFridgeMQTT.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DF_RELEASE")]
	public partial class DeviceTrackingDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DeviceTrackingDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DeviceTrackingDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeviceTrackingDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeviceTrackingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeviceTrackingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInfoDeviceActivity")]
		public ISingleResult<GetInfoDeviceActivityResult> GetInfoDeviceActivity([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string strThietBiID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="DateTime")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strThietBiID, fromDate, toDate);
			return ((ISingleResult<GetInfoDeviceActivityResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInfoDeviceModify")]
		public ISingleResult<GetInfoDeviceModifyResult> GetInfoDeviceModify([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string strThietBiID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="DateTime")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strThietBiID, fromDate, toDate);
			return ((ISingleResult<GetInfoDeviceModifyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInfoDeviceMove")]
		public ISingleResult<GetInfoDeviceMoveResult> GetInfoDeviceMove([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string strThietBiID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="DateTime")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strThietBiID, fromDate, toDate);
			return ((ISingleResult<GetInfoDeviceMoveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInfoDeviceReport")]
		public ISingleResult<GetInfoDeviceReportResult> GetInfoDeviceReport([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string strThietBiID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="DateTime")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strThietBiID, fromDate, toDate);
			return ((ISingleResult<GetInfoDeviceReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTreeThiet_ById")]
		public ISingleResult<GetTreeThiet_ByIdResult> GetTreeThiet_ById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EquiqmentId", DbType="VarChar(200)")] string equiqmentId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsContruction", DbType="Bit")] System.Nullable<bool> isContruction)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), equiqmentId, isContruction);
			return ((ISingleResult<GetTreeThiet_ByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_GetInfoDeviceById")]
		public ISingleResult<Sp_GetInfoDeviceByIdResult> Sp_GetInfoDeviceById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ThietBiId", DbType="VarChar(200)")] string thietBiId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thietBiId);
			return ((ISingleResult<Sp_GetInfoDeviceByIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateThieBiSatusMess")]
		public int UpdateThieBiSatusMess([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string strThietBiID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommandType", DbType="NVarChar(200)")] string commandType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommandId", DbType="NVarChar(200)")] string commandId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CommandAction", DbType="NVarChar(200)")] string commandAction, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Loai", DbType="Int")] System.Nullable<int> loai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusMay", DbType="Int")] System.Nullable<int> statusMay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Time", DbType="Float")] System.Nullable<double> time, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrangThaiHienTai", DbType="Int")] System.Nullable<int> trangThaiHienTai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LatitudeHienTai", DbType="Decimal(18,10)")] System.Nullable<decimal> latitudeHienTai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LongtitudeHienTai", DbType="Decimal(18,10)")] System.Nullable<decimal> longtitudeHienTai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strThietBiID, commandType, commandId, commandAction, loai, statusMay, time, trangThaiHienTai, latitudeHienTai, longtitudeHienTai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_GetInfoDevice")]
		public ISingleResult<Sp_GetInfoDeviceResult> Sp_GetInfoDevice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StrCongTrinhID", DbType="NVarChar(250)")] string strCongTrinhID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strCongTrinhID);
			return ((ISingleResult<Sp_GetInfoDeviceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTreeThietBi")]
		public ISingleResult<GetTreeThietBiResult> GetTreeThietBi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StrCongTrinhID", DbType="NVarChar(250)")] string strCongTrinhID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strCongTrinhID);
			return ((ISingleResult<GetTreeThietBiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCong")]
		public ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongResult> CongTrinhGetInfoBCQuyTrinhThiCong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCongCoc")]
		public ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongCocResult> CongTrinhGetInfoBCQuyTrinhThiCongCoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CocId", DbType="NVarChar(500)")] string cocId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, cocId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongCocResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoCongTrinhNhanVien", IsComposable=true)]
		public object CongTrinhGetInfoCongTrinhNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoDSNhanVien")]
		public ISingleResult<CongTrinhGetInfoDSNhanVienResult> CongTrinhGetInfoDSNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoDSNhanVienResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInfoCongTrinh")]
		public ISingleResult<GetInfoCongTrinhResult> GetInfoCongTrinh([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NameCongTring", DbType="NVarChar(500)")] string nameCongTring)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nameCongTring);
			return ((ISingleResult<GetInfoCongTrinhResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoQuanLyThuChi")]
		public ISingleResult<CongTrinhGetInfoQuanLyThuChiResult> CongTrinhGetInfoQuanLyThuChi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoQuanLyThuChiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCVatTu")]
		public ISingleResult<CongTrinhGetInfoBCVatTuResult> CongTrinhGetInfoBCVatTu([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCVatTuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCSanLuong")]
		public ISingleResult<CongTrinhGetInfoBCSanLuongResult> CongTrinhGetInfoBCSanLuong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCSanLuongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_GetInfoDeviceByIdAll")]
		public ISingleResult<Sp_GetInfoDeviceByIdAllResult> Sp_GetInfoDeviceByIdAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Sp_GetInfoDeviceByIdAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCThietbi")]
		public ISingleResult<CongTrinhGetInfoBCThietbiResult> CongTrinhGetInfoBCThietbi([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCThietbiResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCongChiTiet")]
		public ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongChiTietResult> CongTrinhGetInfoBCQuyTrinhThiCongChiTiet([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhId", DbType="NVarChar(500)")] string congTrinhId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CocId", DbType="NVarChar(500)")] string cocId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromDate", DbType="Date")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToDate", DbType="Date")] System.Nullable<System.DateTime> toDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhId, cocId, fromDate, toDate);
			return ((ISingleResult<CongTrinhGetInfoBCQuyTrinhThiCongChiTietResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _Password;
		
		private System.Nullable<System.Guid> _NhanVienId;
		
		private bool _IsActive;
		
		private System.DateTime _LastSync;
		
		private string _PassLock;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNhanVienIdChanging(System.Nullable<System.Guid> value);
    partial void OnNhanVienIdChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnLastSyncChanging(System.DateTime value);
    partial void OnLastSyncChanged();
    partial void OnPassLockChanging(string value);
    partial void OnPassLockChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> NhanVienId
		{
			get
			{
				return this._NhanVienId;
			}
			set
			{
				if ((this._NhanVienId != value))
				{
					this.OnNhanVienIdChanging(value);
					this.SendPropertyChanging();
					this._NhanVienId = value;
					this.SendPropertyChanged("NhanVienId");
					this.OnNhanVienIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSync", DbType="DateTime NOT NULL")]
		public System.DateTime LastSync
		{
			get
			{
				return this._LastSync;
			}
			set
			{
				if ((this._LastSync != value))
				{
					this.OnLastSyncChanging(value);
					this.SendPropertyChanging();
					this._LastSync = value;
					this.SendPropertyChanged("LastSync");
					this.OnLastSyncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassLock", DbType="NVarChar(20)")]
		public string PassLock
		{
			get
			{
				return this._PassLock;
			}
			set
			{
				if ((this._PassLock != value))
				{
					this.OnPassLockChanging(value);
					this.SendPropertyChanging();
					this._PassLock = value;
					this.SendPropertyChanged("PassLock");
					this.OnPassLockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetInfoDeviceActivityResult
	{
		
		private System.Guid _ThietBiID;
		
		private string _DeviceId;
		
		private string _ThoiGianHoatDong;
		
		private string _LanThayDauTiepTheo;
		
		private string _LanThayLocTiepTheo;
		
		private string _ThoiGian;
		
		private System.Nullable<int> _Loai;
		
		private System.Nullable<double> _Time;
		
		private System.Nullable<int> _TrangThai;
		
		private string _StrTrangThai;
		
		public GetInfoDeviceActivityResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ThietBiID
		{
			get
			{
				return this._ThietBiID;
			}
			set
			{
				if ((this._ThietBiID != value))
				{
					this._ThietBiID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this._DeviceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoatDong", DbType="NVarChar(100)")]
		public string ThoiGianHoatDong
		{
			get
			{
				return this._ThoiGianHoatDong;
			}
			set
			{
				if ((this._ThoiGianHoatDong != value))
				{
					this._ThoiGianHoatDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanThayDauTiepTheo", DbType="NVarChar(100)")]
		public string LanThayDauTiepTheo
		{
			get
			{
				return this._LanThayDauTiepTheo;
			}
			set
			{
				if ((this._LanThayDauTiepTheo != value))
				{
					this._LanThayDauTiepTheo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanThayLocTiepTheo", DbType="NVarChar(100)")]
		public string LanThayLocTiepTheo
		{
			get
			{
				return this._LanThayLocTiepTheo;
			}
			set
			{
				if ((this._LanThayLocTiepTheo != value))
				{
					this._LanThayLocTiepTheo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(100)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Int")]
		public System.Nullable<int> Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this._Loai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="Float")]
		public System.Nullable<double> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this._Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrTrangThai", DbType="NVarChar(17) NOT NULL", CanBeNull=false)]
		public string StrTrangThai
		{
			get
			{
				return this._StrTrangThai;
			}
			set
			{
				if ((this._StrTrangThai != value))
				{
					this._StrTrangThai = value;
				}
			}
		}
	}
	
	public partial class GetInfoDeviceModifyResult
	{
		
		private string _NgayBaoSua;
		
		private string _NgaySua;
		
		private string _NgayHoanTat;
		
		private string _DonViSua;
		
		private string _DiaDiemSua;
		
		private string _MoTa;
		
		private string _ChiPhi;
		
		public GetInfoDeviceModifyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBaoSua", DbType="NVarChar(100)")]
		public string NgayBaoSua
		{
			get
			{
				return this._NgayBaoSua;
			}
			set
			{
				if ((this._NgayBaoSua != value))
				{
					this._NgayBaoSua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySua", DbType="NVarChar(100)")]
		public string NgaySua
		{
			get
			{
				return this._NgaySua;
			}
			set
			{
				if ((this._NgaySua != value))
				{
					this._NgaySua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHoanTat", DbType="NVarChar(100)")]
		public string NgayHoanTat
		{
			get
			{
				return this._NgayHoanTat;
			}
			set
			{
				if ((this._NgayHoanTat != value))
				{
					this._NgayHoanTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViSua", DbType="NVarChar(200)")]
		public string DonViSua
		{
			get
			{
				return this._DonViSua;
			}
			set
			{
				if ((this._DonViSua != value))
				{
					this._DonViSua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiemSua", DbType="NVarChar(200)")]
		public string DiaDiemSua
		{
			get
			{
				return this._DiaDiemSua;
			}
			set
			{
				if ((this._DiaDiemSua != value))
				{
					this._DiaDiemSua = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(500)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiPhi", DbType="NVarChar(200)")]
		public string ChiPhi
		{
			get
			{
				return this._ChiPhi;
			}
			set
			{
				if ((this._ChiPhi != value))
				{
					this._ChiPhi = value;
				}
			}
		}
	}
	
	public partial class GetInfoDeviceMoveResult
	{
		
		private string _Ngay;
		
		private string _TuViTri;
		
		private string _DenViTri;
		
		private System.DateTime _Thoigian;
		
		public GetInfoDeviceMoveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay", DbType="NVarChar(100)")]
		public string Ngay
		{
			get
			{
				return this._Ngay;
			}
			set
			{
				if ((this._Ngay != value))
				{
					this._Ngay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuViTri", DbType="NVarChar(500)")]
		public string TuViTri
		{
			get
			{
				return this._TuViTri;
			}
			set
			{
				if ((this._TuViTri != value))
				{
					this._TuViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenViTri", DbType="NVarChar(500)")]
		public string DenViTri
		{
			get
			{
				return this._DenViTri;
			}
			set
			{
				if ((this._DenViTri != value))
				{
					this._DenViTri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigian", DbType="DateTime NOT NULL")]
		public System.DateTime Thoigian
		{
			get
			{
				return this._Thoigian;
			}
			set
			{
				if ((this._Thoigian != value))
				{
					this._Thoigian = value;
				}
			}
		}
	}
	
	public partial class GetInfoDeviceReportResult
	{
		
		private System.Nullable<System.Guid> _ThietBiID;
		
		private string _ThoiGian;
		
		private string _strTrangThai;
		
		private string _strTinhTrang;
		
		private string _GhiChu;
		
		private string _AvatarThietBi;
		
		private string _HinhAnh;
		
		public GetInfoDeviceReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ThietBiID
		{
			get
			{
				return this._ThietBiID;
			}
			set
			{
				if ((this._ThietBiID != value))
				{
					this._ThietBiID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(100)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTrangThai", DbType="NVarChar(500)")]
		public string strTrangThai
		{
			get
			{
				return this._strTrangThai;
			}
			set
			{
				if ((this._strTrangThai != value))
				{
					this._strTrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTinhTrang", DbType="NVarChar(500)")]
		public string strTinhTrang
		{
			get
			{
				return this._strTinhTrang;
			}
			set
			{
				if ((this._strTinhTrang != value))
				{
					this._strTinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvatarThietBi", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string AvatarThietBi
		{
			get
			{
				return this._AvatarThietBi;
			}
			set
			{
				if ((this._AvatarThietBi != value))
				{
					this._AvatarThietBi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
	}
	
	public partial class GetTreeThiet_ByIdResult
	{
		
		private string _Id;
		
		private string _Name;
		
		private string _Father;
		
		private int _Cap;
		
		private System.Nullable<decimal> _LatitudeHienTai;
		
		private System.Nullable<decimal> _LongtitudeHienTai;
		
		public GetTreeThiet_ByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Father", DbType="NVarChar(50)")]
		public string Father
		{
			get
			{
				return this._Father;
			}
			set
			{
				if ((this._Father != value))
				{
					this._Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int NOT NULL")]
		public int Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatitudeHienTai", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> LatitudeHienTai
		{
			get
			{
				return this._LatitudeHienTai;
			}
			set
			{
				if ((this._LatitudeHienTai != value))
				{
					this._LatitudeHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongtitudeHienTai", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> LongtitudeHienTai
		{
			get
			{
				return this._LongtitudeHienTai;
			}
			set
			{
				if ((this._LongtitudeHienTai != value))
				{
					this._LongtitudeHienTai = value;
				}
			}
		}
	}
	
	public partial class Sp_GetInfoDeviceByIdResult
	{
		
		private System.Nullable<long> _STT;
		
		private string _HinhAnhAvatar;
		
		private string _ThietBiId;
		
		private string _TenCongTrinh;
		
		private string _DiaDiem;
		
		private string _TenVietTat;
		
		private string _TenThietBi;
		
		private System.Nullable<int> _TrangThai;
		
		private string _strTinhTrang;
		
		private System.Nullable<int> _TrangThaiHienTai;
		
		private string _StrTrangThai;
		
		private string _DaHoatDong;
		
		private string _LoaiHinh;
		
		private string _ThoiGianVao;
		
		private string _NgayOCongTrinh;
		
		private string _GiaThue;
		
		private string _ThanhTien;
		
		private string _ThayDauLanCuoi;
		
		private string _ThayLocLanCuoi;
		
		private string _SoGioThayDau;
		
		private string _SoGioThayLoc;
		
		private System.Nullable<double> _ThayDauTiep;
		
		private System.Nullable<double> _ThayLocTiep;
		
		private decimal _Latitude;
		
		private decimal _Longitude;
		
		public Sp_GetInfoDeviceByIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="BigInt")]
		public System.Nullable<long> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhAvatar", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string HinhAnhAvatar
		{
			get
			{
				return this._HinhAnhAvatar;
			}
			set
			{
				if ((this._HinhAnhAvatar != value))
				{
					this._HinhAnhAvatar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ThietBiId
		{
			get
			{
				return this._ThietBiId;
			}
			set
			{
				if ((this._ThietBiId != value))
				{
					this._ThietBiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500)")]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(1000)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVietTat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenVietTat
		{
			get
			{
				return this._TenVietTat;
			}
			set
			{
				if ((this._TenVietTat != value))
				{
					this._TenVietTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThietBi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenThietBi
		{
			get
			{
				return this._TenThietBi;
			}
			set
			{
				if ((this._TenThietBi != value))
				{
					this._TenThietBi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTinhTrang", DbType="NVarChar(500)")]
		public string strTinhTrang
		{
			get
			{
				return this._strTinhTrang;
			}
			set
			{
				if ((this._strTinhTrang != value))
				{
					this._strTinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHienTai", DbType="Int")]
		public System.Nullable<int> TrangThaiHienTai
		{
			get
			{
				return this._TrangThaiHienTai;
			}
			set
			{
				if ((this._TrangThaiHienTai != value))
				{
					this._TrangThaiHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrTrangThai", DbType="NVarChar(500)")]
		public string StrTrangThai
		{
			get
			{
				return this._StrTrangThai;
			}
			set
			{
				if ((this._StrTrangThai != value))
				{
					this._StrTrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHoatDong", DbType="NVarChar(30)")]
		public string DaHoatDong
		{
			get
			{
				return this._DaHoatDong;
			}
			set
			{
				if ((this._DaHoatDong != value))
				{
					this._DaHoatDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinh", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string LoaiHinh
		{
			get
			{
				return this._LoaiHinh;
			}
			set
			{
				if ((this._LoaiHinh != value))
				{
					this._LoaiHinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianVao", DbType="NVarChar(100)")]
		public string ThoiGianVao
		{
			get
			{
				return this._ThoiGianVao;
			}
			set
			{
				if ((this._ThoiGianVao != value))
				{
					this._ThoiGianVao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayOCongTrinh", DbType="NVarChar(55)")]
		public string NgayOCongTrinh
		{
			get
			{
				return this._NgayOCongTrinh;
			}
			set
			{
				if ((this._NgayOCongTrinh != value))
				{
					this._NgayOCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="NVarChar(200)")]
		public string GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this._GiaThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="NVarChar(200)")]
		public string ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayDauLanCuoi", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ThayDauLanCuoi
		{
			get
			{
				return this._ThayDauLanCuoi;
			}
			set
			{
				if ((this._ThayDauLanCuoi != value))
				{
					this._ThayDauLanCuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayLocLanCuoi", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ThayLocLanCuoi
		{
			get
			{
				return this._ThayLocLanCuoi;
			}
			set
			{
				if ((this._ThayLocLanCuoi != value))
				{
					this._ThayLocLanCuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioThayDau", DbType="NVarChar(250)")]
		public string SoGioThayDau
		{
			get
			{
				return this._SoGioThayDau;
			}
			set
			{
				if ((this._SoGioThayDau != value))
				{
					this._SoGioThayDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioThayLoc", DbType="NVarChar(250)")]
		public string SoGioThayLoc
		{
			get
			{
				return this._SoGioThayLoc;
			}
			set
			{
				if ((this._SoGioThayLoc != value))
				{
					this._SoGioThayLoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayDauTiep", DbType="Float")]
		public System.Nullable<double> ThayDauTiep
		{
			get
			{
				return this._ThayDauTiep;
			}
			set
			{
				if ((this._ThayDauTiep != value))
				{
					this._ThayDauTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayLocTiep", DbType="Float")]
		public System.Nullable<double> ThayLocTiep
		{
			get
			{
				return this._ThayLocTiep;
			}
			set
			{
				if ((this._ThayLocTiep != value))
				{
					this._ThayLocTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
	
	public partial class Sp_GetInfoDeviceResult
	{
		
		private System.Nullable<long> _STT;
		
		private string _ThietBiId;
		
		private string _TenCongTrinh;
		
		private string _DiaDiem;
		
		private string _TenVietTat;
		
		private string _TenThietBi;
		
		private System.Nullable<int> _TrangThai;
		
		private string _DaHoatDong;
		
		private string _LoaiHinh;
		
		private System.Nullable<System.DateTime> _ThoiGianVao;
		
		private System.Nullable<int> _NgayOCongTrinh;
		
		private string _GiaThue;
		
		private System.Nullable<double> _ThanhTien;
		
		private System.Nullable<double> _ThayDauTiep;
		
		private System.Nullable<double> _ThayLocTiep;
		
		private int _TrangThaiHienTai;
		
		private string _StrTrangThai;
		
		private decimal _Latitude;
		
		private decimal _Longitude;
		
		public Sp_GetInfoDeviceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="BigInt")]
		public System.Nullable<long> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiId", DbType="NVarChar(250)")]
		public string ThietBiId
		{
			get
			{
				return this._ThietBiId;
			}
			set
			{
				if ((this._ThietBiId != value))
				{
					this._ThietBiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(1000)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVietTat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenVietTat
		{
			get
			{
				return this._TenVietTat;
			}
			set
			{
				if ((this._TenVietTat != value))
				{
					this._TenVietTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThietBi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenThietBi
		{
			get
			{
				return this._TenThietBi;
			}
			set
			{
				if ((this._TenThietBi != value))
				{
					this._TenThietBi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHoatDong", DbType="NVarChar(30)")]
		public string DaHoatDong
		{
			get
			{
				return this._DaHoatDong;
			}
			set
			{
				if ((this._DaHoatDong != value))
				{
					this._DaHoatDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinh", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string LoaiHinh
		{
			get
			{
				return this._LoaiHinh;
			}
			set
			{
				if ((this._LoaiHinh != value))
				{
					this._LoaiHinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianVao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianVao
		{
			get
			{
				return this._ThoiGianVao;
			}
			set
			{
				if ((this._ThoiGianVao != value))
				{
					this._ThoiGianVao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayOCongTrinh", DbType="Int")]
		public System.Nullable<int> NgayOCongTrinh
		{
			get
			{
				return this._NgayOCongTrinh;
			}
			set
			{
				if ((this._NgayOCongTrinh != value))
				{
					this._NgayOCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="NVarChar(200)")]
		public string GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this._GiaThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayDauTiep", DbType="Float")]
		public System.Nullable<double> ThayDauTiep
		{
			get
			{
				return this._ThayDauTiep;
			}
			set
			{
				if ((this._ThayDauTiep != value))
				{
					this._ThayDauTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayLocTiep", DbType="Float")]
		public System.Nullable<double> ThayLocTiep
		{
			get
			{
				return this._ThayLocTiep;
			}
			set
			{
				if ((this._ThayLocTiep != value))
				{
					this._ThayLocTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHienTai", DbType="Int NOT NULL")]
		public int TrangThaiHienTai
		{
			get
			{
				return this._TrangThaiHienTai;
			}
			set
			{
				if ((this._TrangThaiHienTai != value))
				{
					this._TrangThaiHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrTrangThai", DbType="NVarChar(17) NOT NULL", CanBeNull=false)]
		public string StrTrangThai
		{
			get
			{
				return this._StrTrangThai;
			}
			set
			{
				if ((this._StrTrangThai != value))
				{
					this._StrTrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
	
	public partial class GetTreeThietBiResult
	{
		
		private string _Id;
		
		private string _Name;
		
		private string _Father;
		
		private int _Cap;
		
		public GetTreeThietBiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50)")]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Father", DbType="NVarChar(50)")]
		public string Father
		{
			get
			{
				return this._Father;
			}
			set
			{
				if ((this._Father != value))
				{
					this._Father = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cap", DbType="Int NOT NULL")]
		public int Cap
		{
			get
			{
				return this._Cap;
			}
			set
			{
				if ((this._Cap != value))
				{
					this._Cap = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCQuyTrinhThiCongResult
	{
		
		private System.Guid _CongTrinhID;
		
		private System.Guid _CocID;
		
		private string _ThoiGian;
		
		private string _TenCoc;
		
		private string _MetDat;
		
		private string _MetDa;
		
		private string _ThiCong;
		
		public CongTrinhGetInfoBCQuyTrinhThiCongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhID
		{
			get
			{
				return this._CongTrinhID;
			}
			set
			{
				if ((this._CongTrinhID != value))
				{
					this._CongTrinhID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CocID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CocID
		{
			get
			{
				return this._CocID;
			}
			set
			{
				if ((this._CocID != value))
				{
					this._CocID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(100)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenCoc
		{
			get
			{
				return this._TenCoc;
			}
			set
			{
				if ((this._TenCoc != value))
				{
					this._TenCoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetDat", DbType="NVarChar(100)")]
		public string MetDat
		{
			get
			{
				return this._MetDat;
			}
			set
			{
				if ((this._MetDat != value))
				{
					this._MetDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetDa", DbType="NVarChar(200)")]
		public string MetDa
		{
			get
			{
				return this._MetDa;
			}
			set
			{
				if ((this._MetDa != value))
				{
					this._MetDa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThiCong", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ThiCong
		{
			get
			{
				return this._ThiCong;
			}
			set
			{
				if ((this._ThiCong != value))
				{
					this._ThiCong = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCQuyTrinhThiCongCocResult
	{
		
		private System.Guid _CongTrinhID;
		
		private System.Guid _CocID;
		
		private string _ThoiGian;
		
		private string _TenCoc;
		
		private string _MetDat;
		
		private string _MetDa;
		
		private string _TongThoiGianThucHien;
		
		private string _TongGio;
		
		public CongTrinhGetInfoBCQuyTrinhThiCongCocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhID
		{
			get
			{
				return this._CongTrinhID;
			}
			set
			{
				if ((this._CongTrinhID != value))
				{
					this._CongTrinhID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CocID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CocID
		{
			get
			{
				return this._CocID;
			}
			set
			{
				if ((this._CocID != value))
				{
					this._CocID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NVarChar(100)")]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenCoc
		{
			get
			{
				return this._TenCoc;
			}
			set
			{
				if ((this._TenCoc != value))
				{
					this._TenCoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetDat", DbType="NVarChar(100)")]
		public string MetDat
		{
			get
			{
				return this._MetDat;
			}
			set
			{
				if ((this._MetDat != value))
				{
					this._MetDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetDa", DbType="NVarChar(200)")]
		public string MetDa
		{
			get
			{
				return this._MetDa;
			}
			set
			{
				if ((this._MetDa != value))
				{
					this._MetDa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongThoiGianThucHien", DbType="NVarChar(200)")]
		public string TongThoiGianThucHien
		{
			get
			{
				return this._TongThoiGianThucHien;
			}
			set
			{
				if ((this._TongThoiGianThucHien != value))
				{
					this._TongThoiGianThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGio", DbType="NVarChar(200)")]
		public string TongGio
		{
			get
			{
				return this._TongGio;
			}
			set
			{
				if ((this._TongGio != value))
				{
					this._TongGio = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoDSNhanVienResult
	{
		
		private System.Guid _NhanVienID;
		
		private string _TenNhanVien;
		
		private string _ChucVu;
		
		private string _NgaySinh;
		
		private string _GioiTinh;
		
		private string _Mobile;
		
		public CongTrinhGetInfoDSNhanVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					this._NhanVienID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this._TenNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this._ChucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(100)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
	}
	
	public partial class GetInfoCongTrinhResult
	{
		
		private System.Guid _CongTrinhId;
		
		private string _TenCongTrinh;
		
		private System.DateTime _NgayKhoiCong;
		
		private System.DateTime _NgayKetThuc;
		
		private int _TrangThai;
		
		private string _DiaDiem;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<double> _Longitude;
		
		public GetInfoCongTrinhResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhId
		{
			get
			{
				return this._CongTrinhId;
			}
			set
			{
				if ((this._CongTrinhId != value))
				{
					this._CongTrinhId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhoiCong", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKhoiCong
		{
			get
			{
				return this._NgayKhoiCong;
			}
			set
			{
				if ((this._NgayKhoiCong != value))
				{
					this._NgayKhoiCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(1000)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoQuanLyThuChiResult
	{
		
		private string _CongTrinhId;
		
		private string _ThuChiName;
		
		private System.Nullable<bool> _ThuChiType;
		
		private string _ThuChiValue;
		
		private int _Tien;
		
		public CongTrinhGetInfoQuanLyThuChiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhId", DbType="VarChar(36) NOT NULL", CanBeNull=false)]
		public string CongTrinhId
		{
			get
			{
				return this._CongTrinhId;
			}
			set
			{
				if ((this._CongTrinhId != value))
				{
					this._CongTrinhId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuChiName", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string ThuChiName
		{
			get
			{
				return this._ThuChiName;
			}
			set
			{
				if ((this._ThuChiName != value))
				{
					this._ThuChiName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuChiType", DbType="Bit")]
		public System.Nullable<bool> ThuChiType
		{
			get
			{
				return this._ThuChiType;
			}
			set
			{
				if ((this._ThuChiType != value))
				{
					this._ThuChiType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuChiValue", DbType="NVarChar(200)")]
		public string ThuChiValue
		{
			get
			{
				return this._ThuChiValue;
			}
			set
			{
				if ((this._ThuChiValue != value))
				{
					this._ThuChiValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Int NOT NULL")]
		public int Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this._Tien = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCVatTuResult
	{
		
		private System.Guid _CongTrinhId;
		
		private System.Guid _VatTuID;
		
		private string _TenCongTrinh;
		
		private string _TenVatTu;
		
		private string _SoLuong;
		
		private string _GiaBan;
		
		private string _ThanhTien;
		
		private System.Nullable<double> _Tien;
		
		public CongTrinhGetInfoBCVatTuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhId
		{
			get
			{
				return this._CongTrinhId;
			}
			set
			{
				if ((this._CongTrinhId != value))
				{
					this._CongTrinhId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatTuID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid VatTuID
		{
			get
			{
				return this._VatTuID;
			}
			set
			{
				if ((this._VatTuID != value))
				{
					this._VatTuID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVatTu", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenVatTu
		{
			get
			{
				return this._TenVatTu;
			}
			set
			{
				if ((this._TenVatTu != value))
				{
					this._TenVatTu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(200)")]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="NVarChar(200)")]
		public string GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this._GiaBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="NVarChar(200)")]
		public string ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Float")]
		public System.Nullable<double> Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this._Tien = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCSanLuongResult
	{
		
		private System.Guid _CongTrinhId;
		
		private string _TenCongTrinh;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _TenCongViec;
		
		private string _DonViTinh;
		
		private string _KhoiLuong;
		
		private string _DaThucHien;
		
		private string _ThanhTien;
		
		private System.Nullable<double> _Tien;
		
		public CongTrinhGetInfoBCSanLuongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhId
		{
			get
			{
				return this._CongTrinhId;
			}
			set
			{
				if ((this._CongTrinhId != value))
				{
					this._CongTrinhId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongViec", DbType="NVarChar(400)")]
		public string TenCongViec
		{
			get
			{
				return this._TenCongViec;
			}
			set
			{
				if ((this._TenCongViec != value))
				{
					this._TenCongViec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50)")]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this._DonViTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="NVarChar(200)")]
		public string KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this._KhoiLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaThucHien", DbType="NVarChar(200)")]
		public string DaThucHien
		{
			get
			{
				return this._DaThucHien;
			}
			set
			{
				if ((this._DaThucHien != value))
				{
					this._DaThucHien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="NVarChar(200)")]
		public string ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Float")]
		public System.Nullable<double> Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this._Tien = value;
				}
			}
		}
	}
	
	public partial class Sp_GetInfoDeviceByIdAllResult
	{
		
		private System.Nullable<long> _STT;
		
		private string _HinhAnhAvatar;
		
		private string _ThietBiId;
		
		private string _TenCongTrinh;
		
		private string _DiaDiem;
		
		private string _TenVietTat;
		
		private string _TenThietBi;
		
		private System.Nullable<int> _TrangThai;
		
		private string _strTinhTrang;
		
		private int _TrangThaiHienTai;
		
		private string _StrTrangThai;
		
		private string _DaHoatDong;
		
		private string _LoaiHinh;
		
		private string _ThoiGianVao;
		
		private string _NgayOCongTrinh;
		
		private string _GiaThue;
		
		private string _ThanhTien;
		
		private string _ThayDauLanCuoi;
		
		private string _ThayLocLanCuoi;
		
		private string _SoGioThayDau;
		
		private string _SoGioThayLoc;
		
		private System.Nullable<double> _ThayDauTiep;
		
		private System.Nullable<double> _ThayLocTiep;
		
		private decimal _Latitude;
		
		private decimal _Longitude;
		
		public Sp_GetInfoDeviceByIdAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="BigInt")]
		public System.Nullable<long> STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnhAvatar", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string HinhAnhAvatar
		{
			get
			{
				return this._HinhAnhAvatar;
			}
			set
			{
				if ((this._HinhAnhAvatar != value))
				{
					this._HinhAnhAvatar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiId", DbType="NVarChar(250)")]
		public string ThietBiId
		{
			get
			{
				return this._ThietBiId;
			}
			set
			{
				if ((this._ThietBiId != value))
				{
					this._ThietBiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(500)")]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this._TenCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(1000)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVietTat", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenVietTat
		{
			get
			{
				return this._TenVietTat;
			}
			set
			{
				if ((this._TenVietTat != value))
				{
					this._TenVietTat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThietBi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenThietBi
		{
			get
			{
				return this._TenThietBi;
			}
			set
			{
				if ((this._TenThietBi != value))
				{
					this._TenThietBi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strTinhTrang", DbType="NVarChar(500)")]
		public string strTinhTrang
		{
			get
			{
				return this._strTinhTrang;
			}
			set
			{
				if ((this._strTinhTrang != value))
				{
					this._strTinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHienTai", DbType="Int NOT NULL")]
		public int TrangThaiHienTai
		{
			get
			{
				return this._TrangThaiHienTai;
			}
			set
			{
				if ((this._TrangThaiHienTai != value))
				{
					this._TrangThaiHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrTrangThai", DbType="NVarChar(500)")]
		public string StrTrangThai
		{
			get
			{
				return this._StrTrangThai;
			}
			set
			{
				if ((this._StrTrangThai != value))
				{
					this._StrTrangThai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaHoatDong", DbType="NVarChar(30)")]
		public string DaHoatDong
		{
			get
			{
				return this._DaHoatDong;
			}
			set
			{
				if ((this._DaHoatDong != value))
				{
					this._DaHoatDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinh", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string LoaiHinh
		{
			get
			{
				return this._LoaiHinh;
			}
			set
			{
				if ((this._LoaiHinh != value))
				{
					this._LoaiHinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianVao", DbType="NVarChar(100)")]
		public string ThoiGianVao
		{
			get
			{
				return this._ThoiGianVao;
			}
			set
			{
				if ((this._ThoiGianVao != value))
				{
					this._ThoiGianVao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayOCongTrinh", DbType="NVarChar(55)")]
		public string NgayOCongTrinh
		{
			get
			{
				return this._NgayOCongTrinh;
			}
			set
			{
				if ((this._NgayOCongTrinh != value))
				{
					this._NgayOCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThue", DbType="NVarChar(200)")]
		public string GiaThue
		{
			get
			{
				return this._GiaThue;
			}
			set
			{
				if ((this._GiaThue != value))
				{
					this._GiaThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="NVarChar(200)")]
		public string ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayDauLanCuoi", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ThayDauLanCuoi
		{
			get
			{
				return this._ThayDauLanCuoi;
			}
			set
			{
				if ((this._ThayDauLanCuoi != value))
				{
					this._ThayDauLanCuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayLocLanCuoi", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ThayLocLanCuoi
		{
			get
			{
				return this._ThayLocLanCuoi;
			}
			set
			{
				if ((this._ThayLocLanCuoi != value))
				{
					this._ThayLocLanCuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioThayDau", DbType="NVarChar(250)")]
		public string SoGioThayDau
		{
			get
			{
				return this._SoGioThayDau;
			}
			set
			{
				if ((this._SoGioThayDau != value))
				{
					this._SoGioThayDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoGioThayLoc", DbType="NVarChar(250)")]
		public string SoGioThayLoc
		{
			get
			{
				return this._SoGioThayLoc;
			}
			set
			{
				if ((this._SoGioThayLoc != value))
				{
					this._SoGioThayLoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayDauTiep", DbType="Float")]
		public System.Nullable<double> ThayDauTiep
		{
			get
			{
				return this._ThayDauTiep;
			}
			set
			{
				if ((this._ThayDauTiep != value))
				{
					this._ThayDauTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThayLocTiep", DbType="Float")]
		public System.Nullable<double> ThayLocTiep
		{
			get
			{
				return this._ThayLocTiep;
			}
			set
			{
				if ((this._ThayLocTiep != value))
				{
					this._ThayLocTiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this._Latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Decimal(18,10) NOT NULL")]
		public decimal Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this._Longitude = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCThietbiResult
	{
		
		private System.Guid _ThietBiId;
		
		private System.Guid _CongTrinhID;
		
		private string _TenThietBi;
		
		private string _DonViThue;
		
		private string _NgayDen;
		
		private string _NgayDi;
		
		private string _DonGia;
		
		private string _SoNgay;
		
		private string _SoTien;
		
		private string _TongNgayOCongTrinh;
		
		private string _TongSoTien;
		
		private System.Nullable<decimal> _Tien;
		
		public CongTrinhGetInfoBCThietbiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ThietBiId
		{
			get
			{
				return this._ThietBiId;
			}
			set
			{
				if ((this._ThietBiId != value))
				{
					this._ThietBiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CongTrinhID
		{
			get
			{
				return this._CongTrinhID;
			}
			set
			{
				if ((this._CongTrinhID != value))
				{
					this._CongTrinhID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThietBi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string TenThietBi
		{
			get
			{
				return this._TenThietBi;
			}
			set
			{
				if ((this._TenThietBi != value))
				{
					this._TenThietBi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViThue", DbType="NVarChar(250)")]
		public string DonViThue
		{
			get
			{
				return this._DonViThue;
			}
			set
			{
				if ((this._DonViThue != value))
				{
					this._DonViThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDen", DbType="NVarChar(100)")]
		public string NgayDen
		{
			get
			{
				return this._NgayDen;
			}
			set
			{
				if ((this._NgayDen != value))
				{
					this._NgayDen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="NVarChar(100)")]
		public string NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this._NgayDi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NVarChar(200)")]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgay", DbType="NVarChar(200)")]
		public string SoNgay
		{
			get
			{
				return this._SoNgay;
			}
			set
			{
				if ((this._SoNgay != value))
				{
					this._SoNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="NVarChar(200)")]
		public string SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this._SoTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongNgayOCongTrinh", DbType="NVarChar(200)")]
		public string TongNgayOCongTrinh
		{
			get
			{
				return this._TongNgayOCongTrinh;
			}
			set
			{
				if ((this._TongNgayOCongTrinh != value))
				{
					this._TongNgayOCongTrinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTien", DbType="NVarChar(200)")]
		public string TongSoTien
		{
			get
			{
				return this._TongSoTien;
			}
			set
			{
				if ((this._TongSoTien != value))
				{
					this._TongSoTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this._Tien = value;
				}
			}
		}
	}
	
	public partial class CongTrinhGetInfoBCQuyTrinhThiCongChiTietResult
	{
		
		private System.Nullable<System.Guid> _CocID;
		
		private System.Nullable<System.Guid> _ThiCongCocID;
		
		private System.Guid _ThiCongID;
		
		private string _ThiCong;
		
		private System.Nullable<double> _ThoiGianThiCong;
		
		private string _strThoiGianThiCong;
		
		private string _strThoiGian;
		
		private System.Nullable<System.DateTime> _ThoiGian;
		
		private string _GhiChu;
		
		private int _ThuTu;
		
		public CongTrinhGetInfoBCQuyTrinhThiCongChiTietResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CocID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CocID
		{
			get
			{
				return this._CocID;
			}
			set
			{
				if ((this._CocID != value))
				{
					this._CocID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThiCongCocID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ThiCongCocID
		{
			get
			{
				return this._ThiCongCocID;
			}
			set
			{
				if ((this._ThiCongCocID != value))
				{
					this._ThiCongCocID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThiCongID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ThiCongID
		{
			get
			{
				return this._ThiCongID;
			}
			set
			{
				if ((this._ThiCongID != value))
				{
					this._ThiCongID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThiCong", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ThiCong
		{
			get
			{
				return this._ThiCong;
			}
			set
			{
				if ((this._ThiCong != value))
				{
					this._ThiCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianThiCong", DbType="Float")]
		public System.Nullable<double> ThoiGianThiCong
		{
			get
			{
				return this._ThoiGianThiCong;
			}
			set
			{
				if ((this._ThoiGianThiCong != value))
				{
					this._ThoiGianThiCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strThoiGianThiCong", DbType="NVarChar(200)")]
		public string strThoiGianThiCong
		{
			get
			{
				return this._strThoiGianThiCong;
			}
			set
			{
				if ((this._strThoiGianThiCong != value))
				{
					this._strThoiGianThiCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strThoiGian", DbType="NVarChar(100)")]
		public string strThoiGian
		{
			get
			{
				return this._strThoiGian;
			}
			set
			{
				if ((this._strThoiGian != value))
				{
					this._strThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this._ThoiGian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(500)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int NOT NULL")]
		public int ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this._ThuTu = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
