<?xml version="1.0" encoding="utf-8"?><Database Name="DF_RELEASE" Class="DeviceTrackingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=45.117.80.39;Initial Catalog=DF_RELEASE;Persist Security Info=True;User ID=sa;Connect Timeout=500" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NhanVienId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastSync" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PassLock" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetInfoDeviceActivity" Method="GetInfoDeviceActivity">
    <Parameter Name="strThietBiID" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetInfoDeviceActivityResult">
      <Column Name="ThietBiID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianHoatDong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LanThayDauTiepTheo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LanThayLocTiepTheo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Loai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Time" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StrTrangThai" Type="System.String" DbType="NVarChar(17) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInfoDeviceModify" Method="GetInfoDeviceModify">
    <Parameter Name="strThietBiID" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetInfoDeviceModifyResult">
      <Column Name="NgayBaoSua" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySua" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayHoanTat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonViSua" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiemSua" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ChiPhi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInfoDeviceMove" Method="GetInfoDeviceMove">
    <Parameter Name="strThietBiID" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetInfoDeviceMoveResult">
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TuViTri" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DenViTri" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Thoigian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInfoDeviceReport" Method="GetInfoDeviceReport">
    <Parameter Name="strThietBiID" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="GetInfoDeviceReportResult">
      <Column Name="ThietBiID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="strTrangThai" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="strTinhTrang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AvatarThietBi" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTreeThiet_ById" Method="GetTreeThiet_ById">
    <Parameter Name="EquiqmentId" Parameter="equiqmentId" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IsContruction" Parameter="isContruction" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetTreeThiet_ByIdResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Father" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LatitudeHienTai" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="LongtitudeHienTai" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sp_GetInfoDeviceById" Method="Sp_GetInfoDeviceById">
    <Parameter Name="ThietBiId" Parameter="thietBiId" Type="System.String" DbType="VarChar(200)" />
    <ElementType Name="Sp_GetInfoDeviceByIdResult">
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HinhAnhAvatar" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ThietBiId" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TenVietTat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strTinhTrang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThaiHienTai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StrTrangThai" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DaHoatDong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiHinh" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianVao" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayOCongTrinh" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="GiaThue" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThayDauLanCuoi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ThayLocLanCuoi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SoGioThayDau" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoGioThayLoc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ThayDauTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThayLocTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateThieBiSatusMess" Method="UpdateThieBiSatusMess">
    <Parameter Name="strThietBiID" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CommandType" Parameter="commandType" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CommandId" Parameter="commandId" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="CommandAction" Parameter="commandAction" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Loai" Parameter="loai" Type="System.Int32" DbType="Int" />
    <Parameter Name="StatusMay" Parameter="statusMay" Type="System.Int32" DbType="Int" />
    <Parameter Name="Time" Parameter="time" Type="System.Double" DbType="Float" />
    <Parameter Name="TrangThaiHienTai" Parameter="trangThaiHienTai" Type="System.Int32" DbType="Int" />
    <Parameter Name="LatitudeHienTai" Parameter="latitudeHienTai" Type="System.Decimal" DbType="Decimal(18,10)" />
    <Parameter Name="LongtitudeHienTai" Parameter="longtitudeHienTai" Type="System.Decimal" DbType="Decimal(18,10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Sp_GetInfoDevice" Method="Sp_GetInfoDevice">
    <Parameter Name="StrCongTrinhID" Parameter="strCongTrinhID" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="Sp_GetInfoDeviceResult">
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ThietBiId" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TenVietTat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaHoatDong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiHinh" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianVao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayOCongTrinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaThue" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThayDauTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThayLocTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TrangThaiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StrTrangThai" Type="System.String" DbType="NVarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTreeThietBi" Method="GetTreeThietBi">
    <Parameter Name="StrCongTrinhID" Parameter="strCongTrinhID" Type="System.String" DbType="NVarChar(250)" />
    <ElementType Name="GetTreeThietBiResult">
      <Column Name="Id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Father" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCong" Method="CongTrinhGetInfoBCQuyTrinhThiCong">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCQuyTrinhThiCongResult">
      <Column Name="CongTrinhID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CocID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenCoc" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MetDat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MetDa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThiCong" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCongCoc" Method="CongTrinhGetInfoBCQuyTrinhThiCongCoc">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="CocId" Parameter="cocId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCQuyTrinhThiCongCocResult">
      <Column Name="CongTrinhID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CocID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenCoc" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MetDat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MetDa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TongThoiGianThucHien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TongGio" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoCongTrinhNhanVien" Method="CongTrinhGetInfoCongTrinhNhanVien" IsComposable="true">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.CongTrinhGetInfoDSNhanVien" Method="CongTrinhGetInfoDSNhanVien">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoDSNhanVienResult">
      <Column Name="NhanVienID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetInfoCongTrinh" Method="GetInfoCongTrinh">
    <Parameter Name="NameCongTring" Parameter="nameCongTring" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="GetInfoCongTrinhResult">
      <Column Name="CongTrinhId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="NgayKhoiCong" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoQuanLyThuChi" Method="CongTrinhGetInfoQuanLyThuChi">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoQuanLyThuChiResult">
      <Column Name="CongTrinhId" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="ThuChiName" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="ThuChiType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ThuChiValue" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCVatTu" Method="CongTrinhGetInfoBCVatTu">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCVatTuResult">
      <Column Name="CongTrinhId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="VatTuID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TenVatTu" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCSanLuong" Method="CongTrinhGetInfoBCSanLuong">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCSanLuongResult">
      <Column Name="CongTrinhId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TenCongViec" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KhoiLuong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DaThucHien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Sp_GetInfoDeviceByIdAll" Method="Sp_GetInfoDeviceByIdAll">
    <ElementType Name="Sp_GetInfoDeviceByIdAllResult">
      <Column Name="STT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HinhAnhAvatar" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ThietBiId" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TenCongTrinh" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TenVietTat" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="strTinhTrang" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThaiHienTai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StrTrangThai" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DaHoatDong" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LoaiHinh" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianVao" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayOCongTrinh" Type="System.String" DbType="NVarChar(55)" CanBeNull="true" />
      <Column Name="GiaThue" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ThayDauLanCuoi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ThayLocLanCuoi" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SoGioThayDau" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoGioThayLoc" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ThayDauTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThayLocTiep" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Decimal" DbType="Decimal(18,10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCThietbi" Method="CongTrinhGetInfoBCThietbi">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCThietbiResult">
      <Column Name="ThietBiId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CongTrinhID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="DonViThue" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NgayDen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayDi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoNgay" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TongNgayOCongTrinh" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TongSoTien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Tien" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CongTrinhGetInfoBCQuyTrinhThiCongChiTiet" Method="CongTrinhGetInfoBCQuyTrinhThiCongChiTiet">
    <Parameter Name="CongTrinhId" Parameter="congTrinhId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="CocId" Parameter="cocId" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="CongTrinhGetInfoBCQuyTrinhThiCongChiTietResult">
      <Column Name="CocID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ThiCongCocID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ThiCongID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ThiCong" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianThiCong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="strThoiGianThiCong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="strThoiGian" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThuTu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>